platform :ios, '11.0'

# Tesseract generates around 204 noisy warnings
inhibit_all_warnings!

target 'ActionableScreenshots' do
  use_frameworks!

  # Tesseract for iOS Pod
    pod 'TesseractOCRiOS', '4.0.0'
end
