platform :ios, '11.0'

# Tesseract generates around 204 noisy warnings
inhibit_all_warnings!

target 'ActionableScreenshots' do
  use_frameworks!

  # Tesseract for iOS Pod
    pod 'TesseractOCRiOS', '4.0.0'
    
  # Realm for database
    pod 'RealmSwift', '3.0.2'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
